export const ACTIVITY_HEADERS = [
  "key",
  "kind",
  "name",
  "type",
  "type_label",
  "application_id",
  "details",
  "state",
  "emoji_name",
  "emoji_id",
  "emoji_animated",
  "url",
  "sync_id",
  "party_id",
  "party_size_current",
  "party_size_max",
  "button_1",
  "button_2",
  "large_image",
  "large_text",
  "small_image",
  "small_text",
  "image_source",
  "first_seen_at",
  "last_active_at",
  "last_started_at",
  "last_ended_at",
  "total_active_ms",
  "total_active_seconds",
  "total_active_minutes",
  "session_count",
  "streak",
  "is_active",
  "song_url",
  "album_url",
  "artist_links_json",
  "last_sync_id",
];

export const SESSION_HEADERS = [
  "session_id",
  "key",
  "kind",
  "name",
  "type",
  "type_label",
  "application_id",
  "details",
  "state",
  "emoji_name",
  "emoji_id",
  "emoji_animated",
  "url",
  "sync_id",
  "party_id",
  "party_size_current",
  "party_size_max",
  "button_1",
  "button_2",
  "large_image",
  "large_text",
  "small_image",
  "small_text",
  "image_source",
  "started_at",
  "ended_at",
  "duration_ms",
  "duration_seconds",
  "duration_minutes",
  "song_url",
  "album_url",
  "artist_links_json",
  "last_sync_id",
];

export const USER_FLAGS = {
  STAFF: 1 << 0,
  PARTNER: 1 << 1,
  HYPESQUAD: 1 << 2,
  BUG_HUNTER_LEVEL_1: 1 << 3,
  HYPESQUAD_ONLINE_HOUSE_1: 1 << 6,
  HYPESQUAD_ONLINE_HOUSE_2: 1 << 7,
  HYPESQUAD_ONLINE_HOUSE_3: 1 << 8,
  PREMIUM_EARLY_SUPPORTER: 1 << 9,
  BUG_HUNTER_LEVEL_2: 1 << 14,
  VERIFIED_BOT: 1 << 16,
  VERIFIED_DEVELOPER: 1 << 17,
  CERTIFIED_MODERATOR: 1 << 18,
  ACTIVE_DEVELOPER: 1 << 22,
};
